// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0lpgQDEmIhkOf_2mcq5IqrZZ4sF_WbhE',
    appId: '1:1099427515724:web:1f09c1aba826d7f442d3e9',
    messagingSenderId: '1099427515724',
    projectId: 'healthfit-app-9aa66',
    authDomain: 'healthfit-app-9aa66.firebaseapp.com',
    storageBucket: 'healthfit-app-9aa66.firebasestorage.app',
    measurementId: 'G-NR78D9L923',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaieDqtce1WtAHmDjg75pmTA_5BW7CsiM',
    appId: '1:1099427515724:android:a6b5d1407a942c3642d3e9',
    messagingSenderId: '1099427515724',
    projectId: 'healthfit-app-9aa66',
    storageBucket: 'healthfit-app-9aa66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAssFe0GYpb-QaQPPjYyqmK3MtChvdGIhY',
    appId: '1:1099427515724:ios:f08d8c0ef474aa6142d3e9',
    messagingSenderId: '1099427515724',
    projectId: 'healthfit-app-9aa66',
    storageBucket: 'healthfit-app-9aa66.firebasestorage.app',
    iosBundleId: 'com.siratalmustaqeem.healthfitlife',
  );
}




